import type { Metadata } from "next";
import { Darker_Grotesque, Montserrat } from "next/font/google";
import "./globals.scss";
import Header from "./components/Header";
import { ConfigProvider } from "antd";
import CustomCursor from "./components/CustomCursor";

const montserrat = Montserrat({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: "Stanislaw Pivovarov",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={montserrat.className}>
        <CustomCursor/>
        <ConfigProvider>
        <Header />
        {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
